### ISSUE TITLE
A little too eager?

### ISSUE THREAD

**Issue by ddossot** [bobrik/docker-image-cleaner#1]
This tool is a great idea, until Docker get their act together and provide a standard way to do this. So big thank you for doing this.

I'm wondering if the cleaner is a little too eager, it tried to remove images that were still in use:

<pre>
2015/02/21 18:38:19 Going to remove e4d0bc841039a8c84b40df104aacd92b5d60cc88d1d2729eef4d4eb48a5eb3e3: docker.jttelectronics.local:5000/jtt-java8-base:latest
2015/02/21 18:38:19 error while removing e4d0bc841039a8c84b40df104aacd92b5d60cc88d1d2729eef4d4eb48a5eb3e3 (docker.jttelectronics.local:5000/jtt-java8-base:latest): API error (409): Conflict, cannot delete e4d0bc841039 because the container 44cbe2b4018b is using it, use -f to force
</pre>

Could this be prevented up front?

**Comment by bobrik** [comment]
Thanks, fixed!
